### PR TITLE
feat(demo): add PWA to docs

### PR DESCRIPTION
**Pull request by santoshyadav198613**

### CODE REVIEW

**Comment by tomastrajan** [comment]
Hey @santoshyadav198613 !

This looks very cool! How does it works with future versions? I didn't really research PWA too much, just  know people had issues when the users had old version which was then hard to clear/ update ?

I guess Angular lib takes care of this but would still be nice to have basic understanding of how its done ? 

Cheers!

**Comment by santoshyadav198613** [comment]
Hi @tomastrajan ,

This is added for docs portal, so now everyone can install the doc's on there mobile and desktop. No changes for core library.

**Comment by tomastrajan** [comment]
@santoshyadav198613 I understand that but about the docs, like service worker caches all the assets which sometimes leads to stale versions for some users, as said before I guess Angular PWA lib takes care of that but would be nice to understand how  :)

**Comment by tomastrajan** [comment]
@santoshyadav198613 also in [offcial docs](https://angular.io/guide/service-worker-getting-started#serving-with-http-server)

> To reduce the possibility of conflicts and avoid serving stale content, test on a dedicated port and disable caching. 

Which sounds scary for prod

**Comment by santoshyadav198613** [comment]
This is how it is taken care of:
Every time the user opens or refreshes the application, the Angular service worker checks for updates to the app by looking for updates to the ngsw.json manifest. If an update is found, it is downloaded and cached automatically, and will be served the next time the application is loaded.

**Comment by tomastrajan** [comment]
@santoshyadav198613 so that means user will be one refresh behind the latest version? How does that interfere with GH pages caching headers ? Can we somehow force refresh if there was a new version  ?

**Comment by santoshyadav198613** [comment]
Hi @tomastrajan ,Yes it will be the case with current implementation, but we can implement SwUpdate to check the updates and push it. I can open a separate PR for that, if you are fine.

**Comment by tomastrajan** [comment]
@santoshyadav198613 ok let;s do that, I will merge this and will be looking forward for the update functionality! Thank you again!

**Comment by santoshyadav198613** [comment]
> @santoshyadav198613 ok let;s do that, I will merge this and will be looking forward for the update functionality! Thank you again!

Thanks a lot, will do that by next week.

**Comment by tomastrajan** [comment]
@santoshyadav198613 it broke demos unfortunately ... how can we revert it so that the SW is removed from people ?

**Comment by tomastrajan** [comment]
@santoshyadav198613 but like OK almost nobody installed in 2 minutes, I just revert and please test it also with demos ( exmaples )

**Comment by santoshyadav198613** [comment]
@tomastrajan , let me check again may be issue with the config , will try to deploy on a temp server to check.

**Comment by tomastrajan** [comment]
@santoshyadav198613 I fixed the PWA by adding ignore `unpkg.com` rule to generated sw configuration, seems to be working. It would be still nice to add this refresh button notification for users ( while keeping this "second visit" ) refresh mechanism  :)

**Comment by santoshyadav198613** [comment]
Awesome @tomastrajan , yes will work on it. Thanks a lot.

**Pull request merged**
