### PR TITLE
Version/6.x

### PR DESCRIPTION
**Pull request by 4F2E4A2E**

### CODE REVIEW

**Comment by tomastrajan** [comment]
@4F2E4A2E hmm, why are there my commits ? I Forked from the HEAD ?

**Comment by 4F2E4A2E** [comment]
>@4F2E4A2E hmm, why are there my commits ? I Forked from the HEAD ?
I created the branch from the `version/7x` branch.

**Comment by tomastrajan** [comment]
Solved

**Comment by 4F2E4A2E** [comment]
Thank you for creating the [version/6.x branch](https://github.com/angular-extensions/elements/tree/version/6.x) and releasing it.

**Pull request closed without merging**
