### PR TITLE
feat: add commitizen support for conventional commits

### PR DESCRIPTION
**Pull request by angelfraga**

### CODE REVIEW

**Comment by tomastrajan** [comment]
Hi @angelfraga !

How is this different from 

```
 "commitlint": {
    "extends": [
      "@commitlint/config-conventional"
    ]
  },
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS",
      "pre-commit": "pretty-quick --staged"
    }
  },

```

what does it add besides what we already have from the already included support ?

**Comment by angelfraga** [comment]
@tomastrajan my intention was just to prepare the project for `git gz` command, I have found out this command very helpful for newbies in conventional commits world (like me 😄).

It shouldn't add new rules, just make that command available in the project folder scope.

That tool should look like this

image

**Comment by tomastrajan** [comment]
@angelfraga ok I see, that sounds great! Please resolve merge conflicts and we can merge  👍

**Comment by angelfraga** [comment]
@tomastrajan, it looks like adding `commitzen` as dev dependency was a mistake and it should be installed globally per each developer. Regarding the second dev dependency `cz-conventional-changelog` and its `package.json` config was fine.  

I am gonna get rid of `commitizen` as dev-dependency and try again 😃

**Comment by tomastrajan** [comment]
@angelfraga thx for your contribution, I am all for making it more convenient for the devs :)

**Pull request merged**
