### PR TITLE
feat(demo): add notification for doc update

### PR DESCRIPTION
**Pull request by santoshyadav198613**
I have added an alert, let me know if it required or we should run it without taking input from user.

### CODE REVIEW

**Comment by tomastrajan** [comment]
Hey @santoshyadav198613 !

Just noticed the PR, sorry for the delay... Anyway, looks good! Thanks for the contribution!

**Comment by tomastrajan** [comment]
@santoshyadav198613 btw was broken, it opened the popup every time (because it was called in the check function and it should have been called only if the update is in fact available). Please test the features you submit... 

```
this.swUpdate.available.pipe(take(1)).subscribe(() => {
      const snack = this.snackbar.open(                                     // <--- this has to be here not outside
        'There is a new version of the docs available',
        'Reload page',
        {
          horizontalPosition: 'center',
          verticalPosition: 'top'
        }
      );
      snack
        .onAction()
        .pipe(take(1))
        .subscribe(() => {
          this.swUpdate.activateUpdate().then(() => window.location.reload());
        });
    });
```

**Comment by santoshyadav198613** [comment]
Ohh I referred this from Angular docs, and was able to see the pop-up after every build while testing locally, sorry for it didn't realize it. Will raise a PR.

**Comment by tomastrajan** [comment]
@santoshyadav198613 already fixed no worries :) The problem was popup was shown always also when there was no update available because it was opened by the check update function which runs every time.

**Pull request merged**
